name: push tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/smoke.cy.js

      - name: Upload Cypress Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 30